<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Ractive Example by tr0y</title>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/css/materialize.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>
    <body>
        <div class="container">
            <table class="ui-list" data-query="all" data-template="list"></table>
        </div>
        <!-- libs -->
        <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="http://cdn.ractivejs.org/latest/ractive.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/js/materialize.min.js"></script>
        <script src="//cdn.jsdelivr.net/ractive.load/latest/ractive-load.min.js"></script>
        <!-- core -->
        <script src="assets/js/system.js"></script>
    </body>
</html>